PLAYING_STRING_DEFAULT = "Playing: %s - %s: %s."
PLAYING_STRING_COMMANDS_DEFAULT = "\nCommands:\n - q (stop),\n - space (pause/resume),\n - a (restart),\n - z (previous)"
PLAYING_STRING_COMMANDS_SPECIAL = PLAYING_STRING_COMMANDS_DEFAULT + "\n - d (next)"
player_actions = ['resume', 'next', 'pause', 'restart', 'previous', 'stop', 'volume']
player_stop = 'stop'
list_of_speech_commands = ['quit', 'single', 'shuffle', 'play', 'voice', 'debug', 'auto', 'select', 'no', 'yes']
quit_string = '406'
alb_mode_string = 'alb'
perf_search_string = 'se'
